[CONFIG]
MODE = DEV
BIT = 64bit
DATEFORMAT = %%Y-%%m-%%d %%p %%I:%%M:%%S
;DATEFORMAT = %%m/%%d/%%Y %%I:%%M:%%S %%p
PERIOD = m
DIGITS = 3

[SOCKET]
IP = 127.0.0.1
PORT = 8180
BUFFER_SIZE = 100 * 1024 * 1024
TIMEOUT = 30

[DATABASE]
DSN = [DBDSN]
DRIVER = Tibero 6 ODBC Driver
IP = [DBIP]
PORT = 8629
DATABASE = [DBNAME]
USER = [DBUSER]
PASSWORD = [DBPASSWORD]
MAX_CONNECTION = 5
MIN_CACHE = 2
MAX_CACHE = 5
MAX_SHARE = 5
#SELECT_TAG_QUERY = SELECT TAGSN, TAG_NM FROM [DBSCHEMA].RDITAG_TB WHERE TAG_USE_YN = 'Y' ORDER BY TAGSN

[HISTORIAN]
IP = [HISTORIANIP]
USER = [HISTORIANUSER]
PASSWORD = [HISTORIANPASSWORD]
;LOCAL_TIME: TRUE or FALSE or Number
LOCAL_TIME = -9

[BIZNEXUS]
IP = [APIIP]
PORT = 8203
